name: Docker Installer Download    # Name of the workflow

# This workflow will download the latest Docker installers and release them as a GitHub release.

on:
  workflow_dispatch:
  schedule: 
    - cron: '0 23 * * *'  # Run at 11:00 PM every day

permissions:
  contents: write  # For checkout action
  packages: write   # For release action

jobs:
  download_installer:
    runs-on: ubuntu-latest  # Run on Ubuntu

    steps:
      - name: Checkout repository # Checkout the repository
        uses: actions/checkout@v4 # v4 is the latest version

      - name: Set up environment # Set up environment variables
        run: |
          sudo apt-get update -y  
          sudo apt-get install -y curl 

      - name: Download installers # Download the latest Docker installers
        run: |
          curl -o install_docker.sh "https://get.docker.com" || (echo "Failed to download install_docker.sh"; exit 1)
          curl -o docker_desktop_installer_windows_x86_64.exe "https://desktop.docker.com/win/main/amd64/Docker%20Desktop%20Installer.exe" || (echo "Failed to download docker_desktop_installer_windows_x86_64.exe"; exit 1)
          curl -o docker_desktop_installer_mac_arm64.dmg "https://desktop.docker.com/mac/main/arm64/Docker.dmg" || (echo "Failed to download docker_desktop_installer_mac_arm64.dmg"; exit 1)
          curl -o docker_desktop_installer_mac_x86_64.dmg "https://desktop.docker.com/mac/main/amd64/Docker.dmg" || (echo "Failed to download docker_desktop_installer_mac_x86_64.dmg"; exit 1)
          curl -o docker_desktop_installer_linux_debian_x86_64.deb "https://desktop.docker.com/linux/main/amd64/149282/docker-desktop-4.30.0-amd64.deb" || (echo "Failed to download docker_desktop_installer_linux_debian_x86_64.deb"; exit 1)
          curl -o docker_desktop_installer_linux_fedora_x86_64.rpm "https://desktop.docker.com/linux/main/amd64/149282/docker-desktop-4.30.0-x86_64.rpm" || (echo "Failed to download docker_desktop_installer_linux_fedora_x86_64.rpm"; exit 1)

      - name: Release   # Release the installers as a GitHub release
        uses: softprops/action-gh-release@v2  # v2 is the latest version
        with:
          files: |                       # List of files to include in the release
            install_docker.sh
            docker_desktop_installer_windows_x86_64.exe
            docker_desktop_installer_mac_arm64.dmg
            docker_desktop_installer_mac_x86_64.dmg
            docker_desktop_installer_linux_debian_x86_64.deb
            docker_desktop_installer_linux_fedora_x86_64.rpm
          tag_name: latest                 # Tag the release as "latest"
          overwrite: true                  # Overwrite any existing release with the same tag name
