name: Docker Installer Download

on:
  workflow_dispatch:
  schedule:
    - cron: '00 23 * * *'

permissions:
  contents: write
  packages: write  # 确保有足够的权限进行发布操作

jobs:
  download_installer:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up environment
      run: sudo apt-get install -y curl

    - name: Download installers
      run: |
         curl -o install_docker.sh "https://get.docker.com" || echo "Failed to download install_docker.sh"
         curl -o docker_desktop_installer_windows_x86_64.exe "https://desktop.docker.com/win/main/amd64/Docker%20Desktop%20Installer.exe" || echo "Failed to download docker_desktop_installer_windows_x86_64.exe"
         curl -o docker_desktop_installer_mac_arm64.dmg "https://desktop.docker.com/mac/main/arm64/Docker.dmg" || echo "Failed to download docker_desktop_installer_mac_arm64.dmg"
         curl -o docker_desktop_installer_mac_x86_64.dmg "https://desktop.docker.com/mac/main/amd64/Docker.dmg" || echo "Failed to download docker_desktop_installer_mac_x86_64.dmg"
         curl -o docker_desktop_installer_linux_debian_x86_64.deb "https://desktop.docker.com/linux/main/amd64/149282/docker-desktop-4.30.0-amd64.deb" || echo "Failed to download docker_desktop_installer_linux_debian_x86_64.deb"
         curl -o docker_desktop_installer_linux_fedora_x86_64.rpm "https://desktop.docker.com/linux/main/amd64/149282/docker-desktop-4.30.0-x86_64.rpm" || echo "Failed to download docker_desktop_installer_linux_fedora_x86_64.rpm"

    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        files: |
          install_docker.sh
          docker_desktop_installer_windows_x86_64.exe
          docker_desktop_installer_mac_arm64.dmg
          docker_desktop_installer_mac_x86_64.dmg
          docker_desktop_installer_linux_debian_x86_64.deb
          docker_desktop_installer_linux_fedora_x86_64.rpm
        tag_name: latest
        overwrite: true # 添加以允许覆盖已有发布
