name: Docker Installer Download

on:
  workflow_dispatch:

permissions:
  contents: write
  packages: write

jobs:
  download_installer:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up environment
        run: |
          sudo apt-get update -y
          sudo apt-get install -y curl jq || { echo "Failed to install required packages"; exit 1; }

      - name: Check curl installation
        run: |
          if ! command -v curl &> /dev/null; then
            echo "curl is not installed. Attempting to install." 
            sudo apt-get install -y curl || { echo "curl installation failed, exiting!" ; exit 1; }
          fi

      - name: Delete old release (v1.0)
        run: |
          echo "Deleting old release v1.0"
          release_response=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            https://api.github.com/repos/${{ github.repository }}/releases/tags/v1.0)
          release_id=$(echo "$release_response" | jq -r .id)

          if [ "$release_id" != "null" ]; then
            curl -s -X DELETE -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
              https://api.github.com/repos/${{ github.repository }}/releases/$release_id
            echo "Old release v1.0 deleted."
          else
            echo "Release v1.0 not found."
          fi

      - name: Retrieve Latest Docker Version
        id: get_latest_version
        run: |
          # 获取最新的 LTS Docker 版本
          latest_version=$(curl -s https://api.github.com/repos/docker/docker-ce/releases | 
            jq -r '.[] | select(.prerelease == false and .tag_name | match("^[0-9]+\\.[0-9]+\\.[0-9]+$")) | .tag_name' | 
            head -n 1) || { echo "Failed to retrieve latest Docker version"; exit 1; }

          if [ -z "$latest_version" ]; then
            echo "No stable Docker version found, exiting."
            exit 1
          fi
          echo "Latest stable Docker version: $latest_version"
          echo "version=$latest_version" >> $GITHUB_ENV

      - name: Download Docker shell script
        run: |
          curl -o install_docker_server.sh "https://get.docker.com" || {
            echo "Failed to download install_docker_server.sh"; 
            exit 1; 
          }

      - name: Download desktop installers
        run: |
          declare -A installers
          installers=(
            ["windows"]="https://desktop.docker.com/win/main/amd64/Docker%20Desktop%20Installer.exe"
            ["mac_arm64"]="https://desktop.docker.com/mac/main/arm64/Docker.dmg"
            ["mac_x86_64"]="https://desktop.docker.com/mac/main/amd64/Docker.dmg"
            ["linux_debian"]="https://desktop.docker.com/linux/main/amd64/latest/docker-desktop-latest-amd64.deb"
            ["linux_fedora"]="https://desktop.docker.com/linux/main/amd64/latest/docker-desktop-latest-x86_64.rpm"
            ["linux_centos"]="https://desktop.docker.com/linux/main/amd64/latest/docker-desktop-latest-x86_64.rpm"
            ["linux_ubuntu"]="https://desktop.docker.com/linux/main/amd64/latest/docker-desktop-latest-amd64.deb"
          )
          
          for key in "${!installers[@]}"; do
            file_name="docker_desktop_installer_${key}"  # 删除时间戳部分
            case "$key" in
              "linux_debian"|"linux_ubuntu") file_name+=".deb" ;;
              "linux_fedora"|"linux_centos") file_name+=".rpm" ;;
              "mac_arm64"|"mac_x86_64") file_name+=".dmg" ;;
              "windows") file_name+=".exe" ;;
              *) echo "Unknown key: $key"; exit 1 ;;
            esac
            
            echo "Downloading $file_name from ${installers[$key]}"
            curl -o "$file_name" "${installers[$key]}" || {
              echo "Failed to download $file_name"; 
              exit 1; 
            }

            # 检查下载文件是否存在
            if [ ! -f "$file_name" ]; then
              echo "$file_name does not exist after download"; 
              exit 1; 
            fi
          done

      - name: Remove timestamped installer files
        run: |
          echo "Removing timestamped files..."
          # 使用模式匹配删除带有时间戳的文件
          find . -type f -name "docker_desktop_installer_*_*" -exec rm -f {} \;

      - name: Create Release
        id: release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: "latest"  # 标记每个发布为最新版本
          body: "Release of Docker Installer latest LTS version for various platforms"
          files: |
            install_docker_server.sh
            docker_desktop_installer_windows.exe
            docker_desktop_installer_mac_arm64.dmg
            docker_desktop_installer_mac_x86_64.dmg
            docker_desktop_installer_linux_debian.deb
            docker_desktop_installer_linux_fedora.rpm
            docker_desktop_installer_linux_centos.rpm
            docker_desktop_installer_linux_ubuntu.deb
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # GitHub 自动提供的 token
