name: Docker Installer Download

on:
  workflow_dispatch:
  schedule:
    - cron: '00 23 * * *'

permissions:
  contents: write
  packages: write
  actions: write

env:
  DOCKER_INSTALLER_URL: "https://get.docker.com"
  DOCKER_DESKTOP_WINDOWS_URL: "https://desktop.docker.com/win/main/amd64/Docker%20Desktop%20Installer.exe"
  DOCKER_DESKTOP_MAC_ARM64_URL: "https://desktop.docker.com/mac/main/arm64/Docker.dmg"
  DOCKER_DESKTOP_MAC_X86_64_URL: "https://desktop.docker.com/mac/main/amd64/Docker.dmg"
  DOCKER_DESKTOP_LINUX_DEBIAN_URL: "https://desktop.docker.com/linux/main/amd64/149282/docker-desktop-4.30.0-amd64.deb"
  DOCKER_DESKTOP_LINUX_FEDORA_URL: "https://desktop.docker.com/linux/main/amd64/149282/docker-desktop-4.30.0-x86_64.rpm"
  QUAY_INSTALLER_URL: "https://quay.io/repository/quay/quay"  # 确保这是正确的下载链接
  GCR_INSTALLER_URL: "https://gcr.io/google-containers/pause"  # 确保这是正确的下载链接
  K8S_GCR_INSTALLER_URL: "https://k8s.gcr.io/v2/google-containers/pause/manifests/latest"  # 确保这是正确的下载链接
  GHCR_INSTALLER_URL: "https://ghcr.io/v2/github/docs/actions/workflow-syntax-for-github-actions"  # 确保这是正确的下载链接
  CLOUDSMITH_INSTALLER_URL: "https://dl.cloudsmith.io/public/cloudsmith/stable/setup.deb.sh"

jobs:
  download_installer:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Download Docker installers
      run: |
         curl -f -o install_docker.sh "${{ env.DOCKER_INSTALLER_URL }}"
         curl -f -o docker_desktop_installer_windows_x86_64.exe "${{ env.DOCKER_DESKTOP_WINDOWS_URL }}"
         curl -f -o docker_desktop_installer_mac_arm64.dmg "${{ env.DOCKER_DESKTOP_MAC_ARM64_URL }}"
         curl -f -o docker_desktop_installer_mac_x86_64.dmg "${{ env.DOCKER_DESKTOP_MAC_X86_64_URL }}"
         curl -f -o docker_desktop_installer_linux_debian_x86_64.deb "${{ env.DOCKER_DESKTOP_LINUX_DEBIAN_URL }}"
         curl -f -o docker_desktop_installer_linux_fedora_x86_64.rpm "${{ env.DOCKER_DESKTOP_LINUX_FEDORA_URL }}"

    - name: Download Quay installer
      run: |
         curl -f -o quay_installer.tar.gz "${{ env.QUAY_INSTALLER_URL }}"

    - name: Download GCR installer
      run: |
         curl -f -o gcr_installer.tar.gz "${{ env.GCR_INSTALLER_URL }}"

    - name: Download K8S GCR installer
      run: |
         curl -f -o k8s_gcr_installer.tar.gz "${{ env.K8S_GCR_INSTALLER_URL }}"

    - name: Download GHCR installer
      run: |
         curl -f -o ghcr_installer.tar.gz "${{ env.GHCR_INSTALLER_URL }}"

    - name: Download Cloudsmith installer
      run: |
         curl -f -o cloudsmith_installer.sh "${{ env.CLOUDSMITH_INSTALLER_URL }}"

    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        files: |
          install_docker.sh
          docker_desktop_installer_windows_x86_64.exe
          docker_desktop_installer_mac_arm64.dmg
          docker_desktop_installer_mac_x86_64.dmg
          docker_desktop_installer_linux_debian_x86_64.deb
          docker_desktop_installer_linux_fedora_x86_64.rpm
          quay_installer.tar.gz
          gcr_installer.tar.gz
          k8s_gcr_installer.tar.gz
          ghcr_installer.tar.gz
          cloudsmith_installer.sh
        tag_name: latest  # 使用具体的版本号
